### ISSUE TITLE
Fatal exception on iOS in Unity 2019.1.10f1

### ISSUE THREAD

**Issue by morty346** [opentok/opentok-unity-samples#4]
# Fatal error in: ../../src/media/engine/webrtcvoiceengine.cc, line 253
# last system error: 0
# Check failed: adm()
# (lldb) 

2019-08-16 12:00:33.157156-0400 ProductName[5763:2008426] [DYMTLInitPlatform] platform initialization successful
2019-08-16 12:00:33.225257-0400 ProductName[5763:2008336] Built from '2019.1/staging' branch, Version '2019.1.10f1 (f007ed779b7a)', Build type 'Development', Scripting Backend 'il2cpp'
2019-08-16 12:00:33.230812-0400 ProductName[5763:2008336] -> registered mono modules 0x10695b600
-> applicationDidFinishLaunching()
PlayerConnection initialized from /var/containers/Bundle/Application/E4799083-3446-4C51-A0C7-029FD608312B/ProductName.app/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55000
Multi-casting "[IP] 192.168.1.215 [Port] 55000 [Flags] 3 [Guid] 1336605907 [EditorId] 663405025 [Version] 1048832 [Id] iPhonePlayer(Gregs-iPad):56000 [Debug] 1 [PackageName] iPhonePlayer" to [225.0.0.222:54997]...
Waiting for connection from host on [0.0.0.0:55000]...
PlayerConnection accepted from [192.168.1.155] handle:0x6
Started listening to [0.0.0.0:55000]
PlayerConnection already initialized - listening to [0.0.0.0:55000]
2019-08-16 12:00:33.630474-0400 ProductName[5763:2008336] Metal GPU Frame Capture Enabled
2019-08-16 12:00:33.630754-0400 ProductName[5763:2008336] Metal API Validation Disabled
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A12X GPU
Initialize engine version: 2019.1.10f1 (f007ed779b7a)
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 5763, TID: 2008537, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001e57536f4 <redacted> + 56
5   CoreMotion                          0x00000001ebf56d7c CoreMotion + 294268
6   CoreMotion                          0x00000001ebf572ac CoreMotion + 295596
7   CoreMotion                          0x00000001ebf571bc CoreMotion + 295356
8   CoreMotion                          0x00000001ebf84ffc CoreMotion + 483324
9   CoreMotion                          0x00000001ebf85040 CoreMotion + 483392
10  CoreFoundation                      0x00000001e64e298c <redacted> + 28
11  CoreFoundation                      0x00000001e64e2274 <redacted> + 276
12  CoreFoundation                      0x00000001e64dd568 <redacted> + 2276
13  CoreFoundation                      0x00000001e64dc964 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001e64dd698 CFRunLoopRun + 84
15  CoreMotion                          0x00000001ebf849d4 CoreMotion + 481748
16  libsystem_pthread.dylib             0x00000001e615b908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001e615b864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001e6163dcc thread_start + 4
2019-08-16 12:00:34.169759-0400 ProductName[5763:2008537] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 5763, TID: 2008537, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001e57536f4 <redacted> + 56
5   CoreMotion                          0x00000001ebf56d7c CoreMotion + 294268
6   CoreMotion                          0x00000001ebf572ac CoreMotion + 295596
7   CoreMotion                          0x00000001ebf571bc CoreMotion + 295356
8   CoreMotion                          0x00000001ebf84ffc CoreMotion + 483324
9   CoreMotion                          0x00000001ebf85040 CoreMotion + 483392
10  CoreFoundation                      0x00000001e64e298c <redacted> + 28
11  CoreFoundation                      0x00000001e64e2274 <redacted> + 276
12  CoreFoundation                      0x00000001e64dd568 <redacted> + 2276
13  CoreFoundation                      0x00000001e64dc964 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001e64dd698 CFRunLoopRun + 84
15  CoreMotion                          0x00000001ebf849d4 CoreMotion + 481748
16  libsystem_pthread.dylib             0x00000001e615b908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001e615b864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001e6163dcc thread_start + 4
UnloadTime: 1.864667 ms
PlayerConnection accepted from [192.168.1.155] handle:0x12
Starting OpenTok sample
0   ProductName                         0x0000000104952970 _Z13GetStacktracei + 88
1   ProductName                         0x00000001051f1488 _Z17DebugStringToFileRK21DebugStringToFileData + 296
2   ProductName                         0x0000000104fbe9fc _ZN15DebugLogHandler12Internal_LogE7LogType9LogOptionN4core12basic_stringIcNS2_20StringStorageDefaultIcEEEEP6Object + 172
3   ProductName                         0x0000000104fbe8e0 _Z35DebugLogHandler_CUSTOM_Internal_Log7LogType9LogOption25ScriptingReferenceWrapperIP12Il2CppStringES1_IP12Il2CppObjectE + 248
4   ProductName                         0x0000000105e58a0c DebugLogHandler_LogFormat_m3C9B0AD4B5CDFF5AF195F9AA9FCBA908053BA41D + 584
5   ProductName                         0x0000000105e72e68 Logger_LogFormat_m7F6CBF8AF6A60EF05CF9EE795502036CBAC847A7 + 900
6   ProductName                         0x0000000105e566d4 Debug_LogFormat_mB23DDD2CD05B2E66F9CF8CA72ECA66C02DCC209E + 600
7   ProductName                         0x0000000105be9f18 SceneScript_Start_m54BC9E7B2277E02B0FD98D32970160BCCAD23165 + 448
8   ProductName                         0x000000010467ecb0 _Z65RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017PFvvEPK10MethodInfoPvPS4_ + 20
9   ProductName                         0x0000000105640a10 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
10  ProductName                         0x0000000104f44a34 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
11  ProductName                         0x0000000104f508bc _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
12  ProductName                         0x0000000104f58198 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr + 1232
13  ProductName                         0x0000000104f582e4 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr + 84
14  ProductName                         0x0000000104f573d4 _ZN13MonoBehaviour16DelayedStartCallEP6ObjectPv + 104
15  ProductName                         0x0000000104b5f310 _ZN18DelayedCallManager6UpdateEi + 764
16  ProductName                         0x0000000104d1fa28 _ZZ23InitPlayerLoopCallbacksvEN50EarlyUpdateScriptRunDelayedStartupFrameRegistrator7ForwardEv + 64
17  ProductName                         0x0000000104d17cd8 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 92
18  ProductName                         0x0000000104d17d34 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 184
19  ProductName                         0x0000000104d17f68 _Z10PlayerLoopv + 256
20  ProductName                         0x000000010524c828 _ZL19UnityPlayerLoopImplb + 56
21  ProductName                         0x000000010462b33c UnityRepaint + 140
22  ProductName                         0x000000010462b228 -[UnityAppController(Rendering) repaintDisplayLink] + 88
23  GPUToolsCore                        0x000000010b01823c -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 204
24  QuartzCore                          0x00000001ea9fbf10 <redacted> + 632
25  QuartzCore                          0x00000001eaac9b3c <redacted> + 276
26  CoreFoundation                      0x00000001e64bb768 <redacted> + 192
27  CoreFoundation                      0x00000001e64e3200 <redacted> + 60
28  CoreFoundation                      0x00000001e64e28f8 <redacted> + 444
29  CoreFoundation                      0x00000001e64dd490 <redacted> + 2060
30  CoreFoundation                      0x00000001e64dc964 CFRunLoopRunSpecific + 452
31  GraphicsServices                    0x00000001e871dd8c GSEventRunModal + 108
32  UIKitCore                           0x000000021365a758 UIApplicationMain + 216
33  ProductName                         0x00000001046245a0 main + 160
34  libdyld.dylib                       0x00000001e5f98fd8 <redacted> + 4
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Creating session
0   ProductName                         0x0000000104952970 _Z13GetStacktracei + 88
1   ProductName                         0x00000001051f1488 _Z17DebugStringToFileRK21DebugStringToFileData + 296
2   ProductName                         0x0000000104fbe9fc _ZN15DebugLogHandler12Internal_LogE7LogType9LogOptionN4core12basic_stringIcNS2_20StringStorageDefaultIcEEEEP6Object + 172
3   ProductName                         0x0000000104fbe8e0 _Z35DebugLogHandler_CUSTOM_Internal_Log7LogType9LogOption25ScriptingReferenceWrapperIP12Il2CppStringES1_IP12Il2CppObjectE + 248
4   ProductName                         0x0000000105e58a0c DebugLogHandler_LogFormat_m3C9B0AD4B5CDFF5AF195F9AA9FCBA908053BA41D + 584
5   ProductName                         0x0000000105e72e68 Logger_LogFormat_m7F6CBF8AF6A60EF05CF9EE795502036CBAC847A7 + 900
6   ProductName                         0x0000000105e566d4 Debug_LogFormat_mB23DDD2CD05B2E66F9CF8CA72ECA66C02DCC209E + 600
7   ProductName                         0x0000000105be543c OpenTokSession__ctor_m7C5138A65259FB63DA71BF1AD2123CE2E7F610D2 + 760
8   ProductName                         0x0000000105be9fa0 SceneScript_Start_m54BC9E7B2277E02B0FD98D32970160BCCAD23165 + 584
9   ProductName                         0x000000010467ecb0 _Z65RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017PFvvEPK10MethodInfoPvPS4_ + 20
10  ProductName                         0x0000000105640a10 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
11  ProductName                         0x0000000104f44a34 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
12  ProductName                         0x0000000104f508bc _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
13  ProductName                         0x0000000104f58198 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr + 1232
14  ProductName                         0x0000000104f582e4 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr + 84
15  ProductName                         0x0000000104f573d4 _ZN13MonoBehaviour16DelayedStartCallEP6ObjectPv + 104
16  ProductName                         0x0000000104b5f310 _ZN18DelayedCallManager6UpdateEi + 764
17  ProductName                         0x0000000104d1fa28 _ZZ23InitPlayerLoopCallbacksvEN50EarlyUpdateScriptRunDelayedStartupFrameRegistrator7ForwardEv + 64
18  ProductName                         0x0000000104d17cd8 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 92
19  ProductName                         0x0000000104d17d34 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 184
20  ProductName                         0x0000000104d17f68 _Z10PlayerLoopv + 256
21  ProductName                         0x000000010524c828 _ZL19UnityPlayerLoopImplb + 56
22  ProductName                         0x000000010462b33c UnityRepaint + 140
23  ProductName                         0x000000010462b228 -[UnityAppController(Rendering) repaintDisplayLink] + 88
24  GPUToolsCore                        0x000000010b01823c -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 204
25  QuartzCore                          0x00000001ea9fbf10 <redacted> + 632
26  QuartzCore                          0x00000001eaac9b3c <redacted> + 276
27  CoreFoundation                      0x00000001e64bb768 <redacted> + 192
28  CoreFoundation                      0x00000001e64e3200 <redacted> + 60
29  CoreFoundation                      0x00000001e64e28f8 <redacted> + 444
30  CoreFoundation                      0x00000001e64dd490 <redacted> + 2060
31  CoreFoundation                      0x00000001e64dc964 CFRunLoopRunSpecific + 452
32  GraphicsServices                    0x00000001e871dd8c GSEventRunModal + 108
33  UIKitCore                           0x000000021365a758 UIApplicationMain + 216
34  ProductName                         0x00000001046245a0 main + 160
35  libdyld.dylib                       0x00000001e5f98fd8 <redacted> + 4
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

2019-08-16 12:00:44.236318-0400 ProductName[5763:2008336] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-08-16 12:00:44.236908-0400 ProductName[5763:2008336] [MC] Reading from public effective user settings.
Connecting...
0   ProductName                         0x0000000104952970 _Z13GetStacktracei + 88
1   ProductName                         0x00000001051f1488 _Z17DebugStringToFileRK21DebugStringToFileData + 296
2   ProductName                         0x0000000104fbe9fc _ZN15DebugLogHandler12Internal_LogE7LogType9LogOptionN4core12basic_stringIcNS2_20StringStorageDefaultIcEEEEP6Object + 172
3   ProductName                         0x0000000104fbe8e0 _Z35DebugLogHandler_CUSTOM_Internal_Log7LogType9LogOption25ScriptingReferenceWrapperIP12Il2CppStringES1_IP12Il2CppObjectE + 248
4   ProductName                         0x0000000105e58a0c DebugLogHandler_LogFormat_m3C9B0AD4B5CDFF5AF195F9AA9FCBA908053BA41D + 584
5   ProductName                         0x0000000105e72e68 Logger_LogFormat_m7F6CBF8AF6A60EF05CF9EE795502036CBAC847A7 + 900
6   ProductName                         0x0000000105e566d4 Debug_LogFormat_mB23DDD2CD05B2E66F9CF8CA72ECA66C02DCC209E + 600
7   ProductName                         0x0000000105be76bc OpenTokSession_Connect_m72AD56DAF56F176F2715E8F5CFAA2D796DEEEC59 + 448
8   ProductName                         0x0000000105bea028 SceneScript_Start_m54BC9E7B2277E02B0FD98D32970160BCCAD23165 + 720
9   ProductName                         0x000000010467ecb0 _Z65RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017PFvvEPK10MethodInfoPvPS4_ + 20
10  ProductName                         0x0000000105640a10 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
11  ProductName                         0x0000000104f44a34 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
12  ProductName                         0x0000000104f508bc _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
13  ProductName                         0x0000000104f58198 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr + 1232
14  ProductName                         0x0000000104f582e4 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr + 84
15  ProductName                         0x0000000104f573d4 _ZN13MonoBehaviour16DelayedStartCallEP6ObjectPv + 104
16  ProductName                         0x0000000104b5f310 _ZN18DelayedCallManager6UpdateEi + 764
17  ProductName                         0x0000000104d1fa28 _ZZ23InitPlayerLoopCallbacksvEN50EarlyUpdateScriptRunDelayedStartupFrameRegistrator7ForwardEv + 64
18  ProductName                         0x0000000104d17cd8 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 92
19  ProductName                         0x0000000104d17d34 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 184
20  ProductName                         0x0000000104d17f68 _Z10PlayerLoopv + 256
21  ProductName                         0x000000010524c828 _ZL19UnityPlayerLoopImplb + 56
22  ProductName                         0x000000010462b33c UnityRepaint + 140
23  ProductName                         0x000000010462b228 -[UnityAppController(Rendering) repaintDisplayLink] + 88
24  GPUToolsCore                        0x000000010b01823c -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 204
25  QuartzCore                          0x00000001ea9fbf10 <redacted> + 632
26  QuartzCore                          0x00000001eaac9b3c <redacted> + 276
27  CoreFoundation                      0x00000001e64bb768 <redacted> + 192
28  CoreFoundation                      0x00000001e64e3200 <redacted> + 60
29  CoreFoundation                      0x00000001e64e28f8 <redacted> + 444
30  CoreFoundation                      0x00000001e64dd490 <redacted> + 2060
31  CoreFoundation                      0x00000001e64dc964 CFRunLoopRunSpecific + 452
32  GraphicsServices                    0x00000001e871dd8c GSEventRunModal + 108
33  UIKitCore                           0x000000021365a758 UIApplicationMain + 216
34  ProductName                         0x00000001046245a0 main + 160
35  libdyld.dylib                       0x00000001e5f98fd8 <redacted> + 4
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 16d60b000 -> priority: 1 
  Thread -> id: 16d57f000 -> priority: 1 
-> applicationWillResignActive()
2019-08-16 12:00:44.978927-0400 ProductName[5763:2008336] [Common] _BSMachError: port d803; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-08-16 12:00:44.979090-0400 ProductName[5763:2008336] [Common] _BSMachError: port d803; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
Session Connected
0   ProductName                         0x0000000104952970 _Z13GetStacktracei + 88
1   ProductName                         0x00000001051f1488 _Z17DebugStringToFileRK21DebugStringToFileData + 296
2   ProductName                         0x0000000104fbe9fc _ZN15DebugLogHandler12Internal_LogE7LogType9LogOptionN4core12basic_stringIcNS2_20StringStorageDefaultIcEEEEP6Object + 172
3   ProductName                         0x0000000104fbe8e0 _Z35DebugLogHandler_CUSTOM_Internal_Log7LogType9LogOption25ScriptingReferenceWrapperIP12Il2CppStringES1_IP12Il2CppObjectE + 248
4   ProductName                         0x0000000105e58a0c DebugLogHandler_LogFormat_m3C9B0AD4B5CDFF5AF195F9AA9FCBA908053BA41D + 584
5   ProductName                         0x0000000105e72448 Logger_Log_m653FDC5B68CB933887D8886762C7BBA75243A9AF + 1128
6   ProductName                         0x0000000105e5638c Debug_Log_m4B7C70BAFD477C6BDB59C88A0934F0B018D03708 + 592
7   ProductName                         0x0000000105be800c OpenTokSession_Session_Connected_m13B9422D5C4233A43B2CA3A6029AA88D3A522AA1 + 396
8   ProductName                         0x000000010467eec8 _Z93RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_RuntimeObjectPFvvEPK10MethodInfoPvPS4_ + 36
9   ProductName                         0x0000000105640a10 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
10  ProductName                         0x00000001056410a8 _ZN6il2cpp2vm7Runtime17InvokeConvertArgsEPK10MethodInfoPvPP12Il2CppObjectiPP15Il2CppException + 508
11  ProductName                         0x00000001056418c0 _ZN6il2cpp2vm12ThreadPoolMs13MessageInvokeEP12Il2CppObjectP19Il2CppMethodMessagePS3_PP11Il2CppArray + 244
12  ProductName                         0x000000010560b760 _ZN6il2cpp6icalls8mscorlib6System7Runtime8Remoting9Messaging11AsyncResult6InvokeEP12Il2CppObject + 76
13  ProductName                         0x00000001065ce2ec ThreadPoolWorkQueue_Dispatch_mCDF7415E4C9D02B34761CAE8EA15CD33DDF85ADF + 888
14  ProductName                         0x000000010467fe84 _Z67RuntimeInvoker_FalseSByte_t9070AEA2966184235653CB9B4D33B149CDA831DFPFvvEPK10MethodInfoPvPS4_ + 32
15  ProductName                         0x0000000105614ac4 _ZL13worker_threadPv + 276
16  ProductName                         0x00000001056379e8 _ZN6il2cpp2vmL11ThreadStartEPv + 80
17  ProductName                         0x0000000105615880 _ZN6il2cpp2os6Thread10RunWrapperEPv + 88
18  ProductName                         0x0000000105617b24 _ZN6il2cpp2os10ThreadImpl18ThreadStartWrapperEPv + 36
19  libsystem_pthread.dylib             0x00000001e615b908 <redacted> + 132
20  libsystem_pthread.dylib             0x00000001e615b864 _pthread_start + 48
21  libsystem_pthread.dylib             0x00000001e6163dcc thread_start + 4
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Creating Publisher
0   ProductName                         0x0000000104952970 _Z13GetStacktracei + 88
1   ProductName                         0x00000001051f1488 _Z17DebugStringToFileRK21DebugStringToFileData + 296
2   ProductName                         0x0000000104fbe9fc _ZN15DebugLogHandler12Internal_LogE7LogType9LogOptionN4core12basic_stringIcNS2_20StringStorageDefaultIcEEEEP6Object + 172
3   ProductName                         0x0000000104fbe8e0 _Z35DebugLogHandler_CUSTOM_Internal_Log7LogType9LogOption25ScriptingReferenceWrapperIP12Il2CppStringES1_IP12Il2CppObjectE + 248
4   ProductName                         0x0000000105e58a0c DebugLogHandler_LogFormat_m3C9B0AD4B5CDFF5AF195F9AA9FCBA908053BA41D + 584
5   ProductName                         0x0000000105e72448 Logger_Log_m653FDC5B68CB933887D8886762C7BBA75243A9AF + 1128
6   ProductName                         0x0000000105e5638c Debug_Log_m4B7C70BAFD477C6BDB59C88A0934F0B018D03708 + 592
7   ProductName                         0x0000000105be80b4 OpenTokSession_Session_Connected_m13B9422D5C4233A43B2CA3A6029AA88D3A522AA1 + 564
8   ProductName                         0x000000010467eec8 _Z93RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_RuntimeObjectPFvvEPK10MethodInfoPvPS4_ + 36
9   ProductName                         0x0000000105640a10 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
10  ProductName                         0x00000001056410a8 _ZN6il2cpp2vm7Runtime17InvokeConvertArgsEPK10MethodInfoPvPP12Il2CppObjectiPP15Il2CppException + 508
11  ProductName                         0x00000001056418c0 _ZN6il2cpp2vm12ThreadPoolMs13MessageInvokeEP12Il2CppObjectP19Il2CppMethodMessagePS3_PP11Il2CppArray + 244
12  ProductName                         0x000000010560b760 _ZN6il2cpp6icalls8mscorlib6System7Runtime8Remoting9Messaging11AsyncResult6InvokeEP12Il2CppObject + 76
13  ProductName                         0x00000001065ce2ec ThreadPoolWorkQueue_Dispatch_mCDF7415E4C9D02B34761CAE8EA15CD33DDF85ADF + 888

14  ProductName                         0x000000010467fe84 _Z67RuntimeInvoker_FalseSByte_t9070AEA2966184235653CB9B4D33B149CDA831DFPFvvEPK10MethodInfoPvPS4_ + 32
15  ProductName                         0x0000000105614ac4 _ZL13worker_threadPv + 276
16  ProductName                         0x00000001056379e8 _ZN6il2cpp2vmL11ThreadStartEPv + 80
17  ProductName                         0x0000000105615880 _ZN6il2cpp2os6Thread10RunWrapperEPv + 88
18  ProductName                         0x0000000105617b24 _ZN6il2cpp2os10ThreadImpl18ThreadStartWrapperEPv + 36
19  libsystem_pthread.dylib             0x00000001e615b908 <redacted> + 132
20  libsystem_pthread.dylib             0x00000001e615b864 _pthread_start + 48
21  libsystem_pthread.dylib             0x00000001e6163dcc thread_start + 4
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

#
# Fatal error in: ../../src/media/engine/webrtcvoiceengine.cc, line 253
# last system error: 0
# Check failed: adm()
# (lldb)

**Comment by vutung92** [comment]
same issues when build and run on ios device .

**Comment by robjperez** [comment]
Please test with last commit in master branch. It should be fixed now.

Going to close the issue, please reopen it if it still does not work
